site_name: Mosaic benchmark
site_url: https://github.com/YasAsgari/Mosaic-benchmark
nav: 
-Home: index.md
-install: installing.md
-tutorial: tutorial.md
-methods: 
 -initialization: initialization.md
 -scenario: scenario_description.md
 -edge_generation: generating_edges.md
 -visualisation: visualisation.md
 -export: export.md


theme: readthedocs